#
# This project constructs ALFA-Campaign door resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTD $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTD del $(OUTPUTDIR)\*.UTD