#
# This project constructs ALFA-Campaign trigger resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTT $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTT del $(OUTPUTDIR)\*.UTT