#
# This project constructs ALFA-Campaign item resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTI $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTI del $(OUTPUTDIR)\*.UTI