#
# This project constructs ALFA-Campaign dialog resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.DLG $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.DLG del $(OUTPUTDIR)\*.DLG