#
# This project constructs ALFA-Campaign effects resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UPE $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UPE del $(OUTPUTDIR)\*.UPE