#
# This project constructs ALFA-Campaign placeable resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTP $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTP del $(OUTPUTDIR)\*.UTP