#
# This project constructs ALFA-Campaign waypoint resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTW $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTW del $(OUTPUTDIR)\*.UTW